
#set_property PACKAGE_PIN L15 [get_ports pmod1[0]]
#set_property PACKAGE_PIN M15 [get_ports pmod1[1]]
#set_property PACKAGE_PIN L14 [get_ports pmod1[2]]
#set_property PACKAGE_PIN M14 [get_ports pmod1[3]]
#set_property PACKAGE_PIN K13 [get_ports pmod1[4]]
#set_property PACKAGE_PIN L13 [get_ports pmod1[5]]
#set_property PACKAGE_PIN N13 [get_ports pmod1[6]]
#set_property PACKAGE_PIN N14 [get_ports pmod1[7]]
set_property PACKAGE_PIN L15 [get_ports B[0]]
set_property PACKAGE_PIN M15 [get_ports B[1]]
set_property PACKAGE_PIN L14 [get_ports B[2]]
set_property PACKAGE_PIN M14 [get_ports B[3]]
set_property PACKAGE_PIN K13 [get_ports R[0]]
set_property PACKAGE_PIN L13 [get_ports R[1]]
set_property PACKAGE_PIN N13 [get_ports R[2]]
set_property PACKAGE_PIN N14 [get_ports R[3]]

#J3 idzie do U2 - J3 jest na dole - PMOD 2
#set_property PACKAGE_PIN P13 [get_ports pmod2[0]]
#set_property PACKAGE_PIN P14 [get_ports pmod2[1]]
#set_property PACKAGE_PIN N11 [get_ports pmod2[2]]
#set_property PACKAGE_PIN N12 [get_ports pmod2[3]]
#set_property PACKAGE_PIN P15 [get_ports pmod2[4]]
#set_property PACKAGE_PIN R15 [get_ports pmod2[5]]
#set_property PACKAGE_PIN R12 [get_ports pmod2[6]]
#set_property PACKAGE_PIN R13 [get_ports pmod2[7]]

set_property PACKAGE_PIN P13 [get_ports HS]
set_property PACKAGE_PIN P14 [get_ports VS]
set_property PACKAGE_PIN P15 [get_ports G[0]]
set_property PACKAGE_PIN R15 [get_ports G[1]]
set_property PACKAGE_PIN R12 [get_ports G[2]]
set_property PACKAGE_PIN R13 [get_ports G[3]]

set_property IOSTANDARD LVCMOS33 [get_ports R*]
set_property IOSTANDARD LVCMOS33 [get_ports G*]
set_property IOSTANDARD LVCMOS33 [get_ports B*]
set_property IOSTANDARD LVCMOS33 [get_ports VS]
set_property IOSTANDARD LVCMOS33 [get_ports HS]